### ISSUE TITLE
question about the model 

### ISSUE THREAD

**Issue by svkucheryavski** [tare/GPMicrobiome#2]
First of all thanks a lot for sharing the STAN model, it is a great help both for understanding the paper and especially for practical use of the method you proposed. I have a couple of questions about the implementation and the use of the model, will be very grateful for your help:

<img width="839" alt="Screenshot 2021-09-30 at 11 13 11" src="https://user-images.githubusercontent.com/2104704/135424207-dbbddf4c-ced9-4171-83d0-068c71e4abd9.png">

In *Supplemental Figure 2: Synthetic data generation* you have the following caption: "*The noise-free relative abundances of 36 bacterial orders are illustrated with black lines. Example sets of noisy relative abundances are illustrated with blue points. Sampled noisy relative abundances are used to generate count data.*"

1. If I understand correctly the black lines — is the average of the posterior samples from `Theta_G` over all iterations. And the noisy abundances come from a random iteration. For example, in this case you have 36 bacterial orders and 80 days, so if I run the model with 1 chain and 1000 iterations, the `Theta_G` will have a dimension of 1000x80x36. So by taking e.g. value from iteration = 100, I will get the simulated noisy abundance values shown as blue points on this picture. Is this correct?

2. Let's say I want to simulate the abundance values for an OTU, which I expect will have an exponential decrease of the abundance with time. In this case I can simply generate theoretical counts by using exponential function, then use them as part of the `OTU_reads` matrix and then select `Theta_G` values for this OTU from a random iteration. Is this correct?

Thanks a lot in advance.

**Comment by tare** [comment]
Hi Sergey,

Thanks for your message! Conceptually, you have correct the understanding of the approach but let me clarify a couple of things. SFig. 2 refers to the approach described in the "Synthetic data generation" section of Supplemental Notes. That is, when using the simulated data to benchmark the proposed method we tried not to use the proposed method to simulate the data. 

`Theta_G` contains the underlying noise-free abundance values. Conceptually, the black lines in SFig. 2 are the posterior means of 'Theta_G'. Moreover, conceptually, the blue points in SFig. 2 visualize one of the samples of 'Theta_F'. That is, `Theta_F` is obtained by adding noise to `Theta_G` and "zeroing"  some of the taxa at specific time points.

Please take a look of this code ([gpmicrobiome.txt](https://github.com/tare/GPMicrobiome/files/7259351/gpmicrobiome.txt)). This code shows how you can use the 'generated quantities' block to simulate counts ("zeroing" is included) from `Theta_G` and `Theta_G_i`. It is basically doing exactly what you described in your second question.

Best,
Tarmo

**Comment by svkucheryavski** [comment]
Hi Tarmo,

thanks a lot for your reply! 

I think it makes a lot of sense now. So strictly speaking the STAN file in this repo returns the Theta G "circle" from the Fig. 1 of the paper — compositions without noise and sampling zeros, right? And if I want to add noise and zeros (and thus get "circle" X from the figure) I have to tune the STAN module "generated quantities" as you showed me in the txt file. 

Will invest some time to learn basics of STAN then.  

With best wishes,
Sergey.

**Comment by tare** [comment]
Exactly. To make your task slightly easier, I modified the code ([gpmicrobiome_noisy.txt](https://github.com/tare/GPMicrobiome/files/7259635/gpmicrobiome_noisy.txt)) further. Now the code will output `Theta^zi` and counts simulated using `Theta^zi`. Please check that the logic makes sense.

Tarmo

**Comment by svkucheryavski** [comment]
Yes it makes even better sense now. Thank you very much for your help!
